# These are supported funding model platforms

# github: [USERNAME]
# patreon: USERNAME
# open_collective: PROJECT
# ko_fi: USERNAME
# tidelift: npm/PACKAGE-NAME
# community_bridge: PROJECT-NAME
# liberapay: USERNAME
# issuehunt: USERNAME
# otechie: USERNAME
# custom: ['https://www.paypal.me/USERNAME', 'https://www.buymeacoffee.com/USERNAME']

