// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH3dl6TLbgx1EgVzRFpfEhN-uiPWK_KeI',
    appId: '1:248267647503:web:e8131d10bf1627f9e6117a',
    messagingSenderId: '248267647503',
    projectId: 'art3mis-app',
    authDomain: 'art3mis-app.firebaseapp.com',
    storageBucket: 'art3mis-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByEcTDaPdqNDi0Jg85X3ZLdfHyTuuW0M4',
    appId: '1:248267647503:android:f82d94332e8758f5e6117a',
    messagingSenderId: '248267647503',
    projectId: 'art3mis-app',
    storageBucket: 'art3mis-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXghzZXZFEFtdtWh7sWlfXXBWvJIt2PwA',
    appId: '1:248267647503:ios:50f16393f058efb0e6117a',
    messagingSenderId: '248267647503',
    projectId: 'art3mis-app',
    storageBucket: 'art3mis-app.firebasestorage.app',
    iosBundleId: 'com.example.artemisApp',
  );
}
